//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftPS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ContactTypeID { get; set; }
        public Nullable<System.Guid> StudentRequestID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual StudentRequest StudentRequest { get; set; }
    }
}
