//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftPS.WebUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DraftPSDbEntities : DbContext
    {
        public DraftPSDbEntities()
            : base("name=DraftPSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<EducationType> EducationType { get; set; }
        public virtual DbSet<InterviewHistory> InterviewHistory { get; set; }
        public virtual DbSet<RequestTracking> RequestTracking { get; set; }
        public virtual DbSet<StudentRequest> StudentRequest { get; set; }
        public virtual DbSet<StudentUniversityRequest> StudentUniversityRequest { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<UniversityDepartment> UniversityDepartment { get; set; }
    }
}
