//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftPS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentRequest()
        {
            this.Contact = new HashSet<Contact>();
            this.InterviewHistory = new HashSet<InterviewHistory>();
            this.StudentUniversityRequest = new HashSet<StudentUniversityRequest>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> AdvisorID { get; set; }
        public Nullable<System.Guid> EducationTypeID { get; set; }
        public Nullable<System.Guid> HomeCityID { get; set; }
        public Nullable<System.Guid> RequestTrackingID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual EducationType EducationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewHistory> InterviewHistory { get; set; }
        public virtual RequestTracking RequestTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentUniversityRequest> StudentUniversityRequest { get; set; }
    }
}
