//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftPS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniversityDepartment()
        {
            this.StudentUniversityRequest = new HashSet<StudentUniversityRequest>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UniversityID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentUniversityRequest> StudentUniversityRequest { get; set; }
        public virtual University University { get; set; }
    }
}
